import { CommunityComment } from "@/types";
import { STUDENT_INFO } from "./booksData";

export const INITIAL_COMMENTS: CommunityComment[] = [
  {
    id: "cmt-1",
    author: `${STUDENT_INFO.name}`,
    avatarColor: "from-cyan-500 to-blue-600",
    role: "Lead Architect & Author",
    isAuthor: true,
    bookId: "all",
    bookTitle: "VibeBooks Engineering Suite",
    rating: 5,
    content: "ยินดีต้อนรับสู่ VibeBooks Community ครับ! พื้นที่นี้เปิดให้ทุกคนแลกเปลี่ยนความคิดเห็น สอบถามสถาปัตยกรรมซอฟต์แวร์ PyQt6, SQLite Parameterized Query, หรือขั้นตอนการสร้าง In-App PDF Reader บน iOS ได้อย่างอิสระครับ",
    likes: 24,
    createdAt: "2026-09-16T08:30:00.000Z",
  },
  {
    id: "cmt-2",
    author: "วรเมธ วิศวกรซอฟต์แวร์",
    avatarColor: "from-purple-500 to-indigo-600",
    role: "Verified Student",
    bookId: "media-player-pro",
    bookTitle: "FastPlayer PRO (Lab 1)",
    rating: 5,
    content: "อ่าน E-book FastPlayer PRO แล้วเข้าใจการใช้ QPainter วาด Vector Icons ขึ้นเยอะมากครับ คมชัดทุก DPI ไม่ต้องพึ่งพาไฟล์รูปภาพ png ภายนอกเลย และระบบ Persistent JSON กู้คืนเพลย์ลิสต์ได้จริง",
    likes: 15,
    createdAt: "2026-09-16T09:15:00.000Z",
  },
  {
    id: "cmt-3",
    author: "ณภัทร สถาปัตย์ระบบ",
    avatarColor: "from-emerald-500 to-teal-600",
    role: "Fullstack Developer",
    bookId: "taskmaster-pro",
    bookTitle: "TaskManagerPRO & Bento (Lab 3 & 4)",
    rating: 5,
    content: "TaskManagerPRO ออกแบบความปลอดภัย SQLite ได้ประทับใจมาก ทั้ง Parameterized Query 100% ป้องกัน SQL Injection และ PBKDF2 Password Hashing มีหน้าสรุป Bento Grid คล้าย Linear App เลยครับ",
    likes: 12,
    createdAt: "2026-09-16T10:45:00.000Z",
  },
  {
    id: "cmt-4",
    author: "กัญญารัตน์ AI Creator",
    avatarColor: "from-amber-500 to-orange-600",
    role: "Creative Coder",
    bookId: "mystic-tarot-altar",
    bookTitle: "Mystic Tarot Oracle (Lab 2)",
    rating: 5,
    content: "ธีม Celestial Altar สีทอง-น้ำเงินเข้มหรูหรามากค่ะ และระบบสุ่มไพ่ 3 ใบไม่ซ้ำกัน 100% พร้อมเสียงบรรเลง 432Hz Harmonic BGM สมาธิตอนใช้งานดีมาก",
    likes: 19,
    createdAt: "2026-09-16T11:20:00.000Z",
  },
];
