import { DigitalProduct, ProductCategory } from '@/types';

export const STORE_INFO = {
  brand: "Book Sangdai",
  brandTh: "บุ๊คสั่งได้",
  tagline: "Ultra-Refined Digital Store & Creator Vault",
  curator: "นายเกียรติภูมิ หารศรีนาถ",
  curatorFull: "นายเกียรติภูมิ หารศรีนาถ (รหัสนักศึกษา: 64332110242-2)",
  curatorEn: "Kiatphum Hansrinath",
  studentId: "64332110242-2",
  supportEmail: "support@booksangdai.store",
};

export interface CategoryInfo {
  id: ProductCategory;
  label: string;
  labelTh: string;
  count: number;
}

export const CATEGORIES: CategoryInfo[] = [
  { id: 'all', label: 'All Vaults', labelTh: 'ทั้งหมด', count: 8 },
  { id: 'ebook', label: 'E-Books & Manuals', labelTh: 'อีบุ๊ค & คู่มือวิศวกรรม', count: 3 },
  { id: 'figma', label: 'Figma UI Kits', labelTh: 'ดีไซน์ซิสเต็ม & Figma', count: 2 },
  { id: 'notion', label: 'Notion Systems', labelTh: 'เทมเพลต Notion OS', count: 1 },
  { id: 'code', label: 'Source Code & SaaS', labelTh: 'ซอร์สโค้ด & สตาร์ทอัพ', count: 1 },
  { id: 'assets', label: '3D & Visual Assets', labelTh: 'กราฟิก 3D & แอสเสท', count: 1 },
];

export const DIGITAL_PRODUCTS: DigitalProduct[] = [
  {
    id: "liquid-glass-apple-ui-kit",
    title: "Liquid Glass Apple-Style UI Kit",
    subtitle: "240+ High-Precision Components, Liquid Optical Glass Tokens & Light/Dark System",
    category: "figma",
    categoryNameTh: "ดีไซน์ซิสเต็ม & Figma",
    price: 390,
    originalPrice: 790,
    rating: 5.0,
    ratingCount: 342,
    badge: "Bestseller",
    isFeatured: true,
    description: "ชุดระบบออกแบบระดับ Flagship ได้รับแรงบันดาลใจจากสถาปัตยกรรม Liquid Glass ของ Apple พร้อมโทเคนสี 48 เฉด, ส่วนประกอบ Auto-layout 5.0 สมบูรณ์แบบ, ไอคอนเวกเตอร์ละเอียดสูง, และเทมเพลตหน้าจอ Mobile & Web Commerce ที่พร้อมส่งต่อสู่ทีมพัฒนาทันที",
    highlights: [
      "240+ Responsive Auto-Layout 5.0 Components",
      "Liquid Glass Translucency Tokens (Blur 24px + Interior 0.5px Rim Highlight)",
      "Adaptive Fluid Grid System (12-Col Desktop + 4-Col Safe-inset Mobile)",
      "Full Light / Dark Mode Switches & Variable Tokens",
    ],
    features: [
      "ไฟล์ Figma (.fig) ตัวจริงพร้อม Auto-layout 5.0",
      "Tailwind CSS Configuration File (colors, shadows, blur)",
      "Style Dictionary & Design Tokens JSON",
      "สิทธิ์ใช้งานเชิงพาณิชย์ Commercial License 100%",
    ],
    specs: {
      release: "v2.4 (2026 Edition)",
      format: "Figma File (.fig) + Tokens JSON",
      version: "2.4.0",
      support: "Lifetime Free Updates",
    },
    fileName: "Liquid_Glass_Apple_UI_Kit.fig.zip",
    fileSize: "48.6 MB",
    fileFormat: "Figma (.fig) + Tokens JSON",
    coverImage: "/products/figma-ui-kit.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "media-player-pro",
    title: "FastPlayer PRO (Media Player Engineering)",
    subtitle: "PyQt6 & QtMultimedia Desktop Engineering (ใบงานที่ 1)",
    category: "ebook",
    categoryNameTh: "อีบุ๊ค & คู่มือวิศวกรรม",
    price: 199,
    originalPrice: 390,
    rating: 4.9,
    ratingCount: 128,
    badge: "Staff Pick",
    isFeatured: true,
    description: "คู่มือสถาปัตยกรรม Desktop Media Player ระดับพรีเมียม พัฒนาด้วย Python, PyQt6 (QtMultimedia) ภายใต้แนวคิด Responsible Vibe Coding ตามเกณฑ์ใบงานที่ 1 ผสมผสาน Obsidian Black & Neon Purple Minimalist Theme, Pure Vector Icon Engine, Interactive Scrubber และ Persistent JSON Storage",
    highlights: [
      "Pure Vector Icon Engine (icons.py): วาดสัญลักษณ์ด้วย QPainter คมชัดทุก DPI 100%",
      "Persistent JSON Storage (Zero Data Loss): จัดเก็บ Playlist, Liked Songs และ Volume",
      "Under Bar Dock: แถบควบคุมมัลติมีเดีย, ปรับระดับเสียง, และ Seek Scrubbing ลื่นไหล",
      "ระบบอัลบั้มและคิวเพลง: เพิ่ม ลบ สลับเพลง และข้ามเพลงอัตโนมัติเมื่อเพลงปัจจุบันจบ",
    ],
    features: [
      "หนังสือ E-book ฉบับเต็ม 120 หน้า (PDF ความละเอียดสูง)",
      "ซอร์สโค้ด Python PyQt6 ตัวเต็มพร้อมรัน",
      "Diagram สถาปัตยกรรมระบบ Class & Signal/Slot",
      "ชุดไอคอน QPainter Vector Icons Engine",
    ],
    specs: {
      release: "v2.5 (Lab 1 Edition)",
      format: "PDF Master + Full Python Source",
      version: "2.5.0",
      support: "Lab Community Forum",
    },
    fileName: "Media_Player_PRO_Engineering.pdf",
    fileSize: "24.8 MB",
    fileFormat: "PDF Digital Master Edition",
    coverImage: "/images/books/media_player.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "apex-pro-next14-boilerplate",
    title: "Apex PRO Next.js 14 E-Commerce Engine",
    subtitle: "Production-grade App Router, Supabase Auth SSR & PromptPay QR Engine",
    category: "code",
    categoryNameTh: "ซอร์สโค้ด & สตาร์ทอัพ",
    price: 490,
    originalPrice: 990,
    badge: "Trending",
    rating: 5.0,
    ratingCount: 189,
    isFeatured: true,
    description: "โครงสร้างระบบ E-Commerce ระดับพรีเมียม Next.js 14 App Router, TypeScript, Supabase SSR Auth, Dynamic PromptPay QR Code Generation, Supabase Storage Private Buckets with Signed URLs, และหน้า Admin Dashboard เต็มรูปแบบ",
    highlights: [
      "Next.js 14 App Router Architecture with Server Components",
      "Supabase SSR (@supabase/ssr) Session Management & OAuth",
      "PromptPay QR Code Generator with Real-time Slip Verification",
      "Admin Analytics Dashboard with Real-time Revenue Sparkline",
    ],
    features: [
      "Git Repository ซอร์สโค้ด Next.js 14 สะอาดระดับ Production",
      "Supabase SQL Schema & RLS Policies Setup Scripts",
      "Private Storage Bucket Security Configuration",
      "คู่มือการ Deploy บน Vercel ภายใน 5 นาที",
    ],
    specs: {
      release: "v2.0 (Next.js 14 & Supabase SSR)",
      format: "Full Source Code Repo (.zip)",
      version: "2.0.0",
      support: "GitHub Discussions Access",
    },
    fileName: "Apex_Pro_ECommerce_Next14.zip",
    fileSize: "15.4 MB",
    fileFormat: "Next.js 14 + Supabase Project ZIP",
    coverImage: "/products/apex-pro.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "mystic-tarot-altar",
    title: "Mystic Tarot 3-Card Oracle System",
    subtitle: "Celestial Altar System & AI Divination Architecture (ใบงานที่ 2)",
    category: "ebook",
    categoryNameTh: "อีบุ๊ค & คู่มือวิศวกรรม",
    price: 259,
    originalPrice: 450,
    rating: 5.0,
    ratingCount: 204,
    badge: "Popular",
    isFeatured: true,
    description: "คู่มือและสถาปัตยกรรมระบบทำนายไพ่ทาโรต์ 3 ใบ (อดีต / ปัจจุบัน / อนาคต) ระดับเดสก์ท็อป พัฒนาด้วย Python 3.14, PyQt6, และ PyInstaller ตามเกณฑ์ใบงานที่ 2 ผสานอัตลักษณ์ Celestial Altar (Dark Luxury & Sacred Gold) จาก Google Stitch, ดนตรีบำบัด 432Hz Harmonic Ambient BGM และ Defensive Vector Fallback",
    highlights: [
      "100% Unique Draw: สุ่มไพ่ 3 ใบไม่ซ้ำกันเด็ดขาดผ่าน random.sample",
      "Celestial Altar Dark Luxury Theme: งานออกแบบพรีเมียมสีทอง-น้ำเงินเข้ม",
      "432Hz Harmonic Ambient BGM: ควบคุมเพลงบรรเลงสมาธิพร้อมปรับระดับเสียง",
      "Defensive Vector Fallback: วาดการ์ดเวกเตอร์ทองคำสำรองอัตโนมัติหากไฟล์สูญหาย",
    ],
    features: [
      "หนังสือ E-book 145 หน้า (PDF Digital Master)",
      "ซอร์สโค้ด Python PyQt6 ระบบไพ่ทาโรต์สมบูรณ์",
      "ระบบเสียง BGM 432Hz คัดสรรพิเศษ",
      "ชุดภาพการ์ดเวกเตอร์ทองคำ Celestial Gold",
    ],
    specs: {
      release: "v3.2 (Lab 2 Edition)",
      format: "PDF Master + Assets",
      version: "3.2.0",
      support: "Lab Community Forum",
    },
    fileName: "Mystic_Tarot_Altar_System.pdf",
    fileSize: "32.4 MB",
    fileFormat: "PDF Digital Master Edition",
    coverImage: "/images/books/tarot_app.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "creator-os-notion-system",
    title: "Ultimate Creator OS & Studio Management",
    subtitle: "All-in-One Notion Architecture for High-Output Digital Creators & Agencies",
    category: "notion",
    categoryNameTh: "เทมเพลต Notion OS",
    price: 249,
    originalPrice: 490,
    rating: 4.9,
    ratingCount: 167,
    badge: "New",
    isFeatured: false,
    description: "ระบบปฏิบัติการ Notion ที่ทรงพลังที่สุดสำหรับครีเอเตอร์และสตูดิโอดิจิทัล รวบรวมระบบจัดการคอนเทนต์แบบ Omnichannel, ระบบจัดการลูกค้า CRM, สัญญาและใบเสนอราคา, การจัดการคลังไฟล์ และแดชบอร์ดการเงินรายเดือน",
    highlights: [
      "Omnichannel Multi-Platform Content Pipeline (YouTube, TikTok, X, Blog)",
      "Client CRM & Digital Product Inventory Management",
      "Automated Monthly Revenue & Expense Analytics",
      "SOP Library & Standard Operating Procedure Checklists",
    ],
    features: [
      "ลิงก์ Notion Template พร้อมกด Duplicate ใช้งานได้ทันที",
      "คู่มือการตั้งค่าและการปรับแต่งระบบอย่างละเอียด (PDF 40 หน้า)",
      "ชุดไอคอน Minimalist Notion Icons กว่า 100 ชิ้น",
      "วิดีโอสาธิตการใช้งาน Step-by-Step",
    ],
    specs: {
      release: "v1.8",
      format: "Notion Link + PDF Manual",
      version: "1.8.0",
      support: "Free System Updates",
    },
    fileName: "Creator_OS_Notion_System.zip",
    fileSize: "8.2 MB",
    fileFormat: "Notion Template Link + PDF Guide",
    coverImage: "/products/creator-branding.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "taskmaster-pro",
    title: "TaskManagerPRO & Bento Kanban Architecture",
    subtitle: "Bento Dashboard & Secure SQLite Architecture (ใบงานที่ 3 & 4)",
    category: "ebook",
    categoryNameTh: "อีบุ๊ค & คู่มือวิศวกรรม",
    price: 179,
    originalPrice: 320,
    rating: 4.8,
    ratingCount: 95,
    badge: "Essential",
    isFeatured: false,
    description: "คู่มือและสถาปัตยกรรมระบบบริหารจัดการภารกิจระดับองค์กร Bento Dashboard & Kanban Board พัฒนาด้วย Python & PyQt6 ตามเกณฑ์ใบงานที่ 3 และ 4 ระบบ Multi-theme Glassmorphism, 100% Parameterized SQLite, PBKDF2 Password Hashing, Soft Delete / Trash Recovery และระบบสำรองข้อมูลอัตโนมัติ",
    highlights: [
      "Bento Grid Dashboard: สรุปตัวเลขสถิติภารกิจและเลย์เอาต์ Bento สไตล์โมเดิร์น",
      "Kanban Workflow: ลำดับสถานะงานแบบเรียลไทม์",
      "ความปลอดภัยระดับ Enterprise: Parameterized Queries 100% และ PBKDF2 Password Hashing",
      "Soft Delete & Trash Recovery: ป้องกันข้อมูลสูญหายด้วยระบบถังขยะและกู้คืนงาน",
    ],
    features: [
      "หนังสือ E-book 135 หน้า (PDF Digital Master)",
      "ซอร์สโค้ด Python PyQt6 Bento Kanban สมบูรณ์",
      "ระบบฐานข้อมูล SQLite พร้อม Migration Scripts",
      "ชุดแบบทดสอบความปลอดภัยและการทำงาน",
    ],
    specs: {
      release: "v2.8 (Lab 3 & 4 Edition)",
      format: "PDF Master + Python Source",
      version: "2.8.0",
      support: "Lab Community Forum",
    },
    fileName: "TaskMaster_PRO_Architecture.pdf",
    fileSize: "18.2 MB",
    fileFormat: "PDF Digital Master Edition",
    coverImage: "/images/books/task_manager.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "liquid-glass-3d-assets",
    title: "3D Liquid Glass Isometric Asset Pack",
    subtitle: "60+ Ultra-Crisp 4K Isometric Renders & Transparent Glass Objects for Modern UI",
    category: "assets",
    categoryNameTh: "กราฟิก 3D & แอสเสท",
    price: 290,
    originalPrice: 590,
    rating: 4.9,
    ratingCount: 112,
    badge: "Trending",
    isFeatured: false,
    description: "ชุดวัตถุ 3D แก้วเหลวความโปร่งใสสูง เรนเดอร์แบบ 4K Alpha Channel พร้อมไฟล์ Blender ต้นฉบับ สำหรับนำไปใช้ใน Hero Banner, Mobile App Cards, Feature Showcase และงานนำเสนอเพื่อเพิ่มมิติความหรูหราให้ผลิตภัณฑ์",
    highlights: [
      "60+ Ultra-High-Resolution 4K Transparent PNGs",
      "Included Blender (.blend) Project Files with Shaders & Lighting",
      "Zero Distortion Optical Refraction Shader Setup",
      "Compatible with Figma, Photoshop, Illustrator, Next.js",
    ],
    features: [
      "ไฟล์ภาพ Transparent PNG คมชัดสูงระดับ 4K",
      "Blender Source File (.blend) พร้อมการจัดแสงสำเร็จรูป",
      "LUTs & Color Grading Presets",
      "Commercial License ใช้งานได้ไม่จำกัดโปรเจกต์",
    ],
    specs: {
      release: "v1.2",
      format: "4K PNGs + Blender Source (.zip)",
      version: "1.2.0",
      support: "Commercial License Included",
    },
    fileName: "Liquid_Glass_3D_Asset_Pack.zip",
    fileSize: "142 MB",
    fileFormat: "4K PNG Pack + Blender Source ZIP",
    coverImage: "/products/liquid-glass-mobile.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
  {
    id: "seller-centre-design-kit",
    title: "Seller Centre & Merchant Flow Kit",
    subtitle: "Enterprise B2B / Merchant Portal UI System with Data-Dense Tables & Analytics",
    category: "figma",
    categoryNameTh: "ดีไซน์ซิสเต็ม & Figma",
    price: 320,
    originalPrice: 650,
    rating: 4.8,
    ratingCount: 78,
    badge: "Staff Pick",
    isFeatured: false,
    description: "ชุดแม่แบบ UI ระบบจัดการร้านค้า (Seller Centre) สำหรับระบบอีคอมเมิร์ซและ B2B SaaS ครบครันด้วย Data Table ที่รองรับ Sorting/Filtering, แดชบอร์ดสรุปยอดขาย, หน้าจัดการคำสั่งซื้อ และระบบจัดการคลังสินค้าดิจิทัล",
    highlights: [
      "Data-Dense Table Components with Sorting, Filtering & Bulk Actions",
      "Sales & Payout Analytics Modules with Interactive Charts",
      "Product Catalog & Vault Storage Management Layouts",
      "WCAG 2.1 AA Accessibility Compliant Color Contrast",
    ],
    features: [
      "ไฟล์ Figma (.fig) 35+ Artboards ระดับ Enterprise",
      "UI Component Library พร้อม Design Tokens",
      "ตัวอย่าง Flow การจัดการคำสั่งซื้อตั้งแต่ต้นจนจบ",
      "ฟรีอัปเดตเวอร์ชันใหม่ตลอด 1 ปี",
    ],
    specs: {
      release: "v1.5",
      format: "Figma File (.fig)",
      version: "1.5.0",
      support: "Free 1-Year Updates",
    },
    fileName: "Seller_Centre_Design_Kit.zip",
    fileSize: "36.2 MB",
    fileFormat: "Figma File (.fig)",
    coverImage: "/products/seller-centre.png",
    curator: STORE_INFO.curatorFull,
    merchantId: 'merchant-demo',
    merchantName: 'นายเกียรติภูมิ หารศรีนาถ',
    merchantPromptPay: '081-234-5678',
  },
];

export function getProductById(id: string): DigitalProduct | undefined {
  return DIGITAL_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: ProductCategory): DigitalProduct[] {
  if (category === 'all') return DIGITAL_PRODUCTS;
  return DIGITAL_PRODUCTS.filter((p) => p.category === category);
}

export function searchProducts(query: string): DigitalProduct[] {
  const q = query.toLowerCase().trim();
  if (!q) return DIGITAL_PRODUCTS;
  return DIGITAL_PRODUCTS.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.subtitle.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      (p.categoryNameTh && p.categoryNameTh.toLowerCase().includes(q))
  );
}
