import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#4cd7f6',
        'surface-container-lowest': '#0f0d18',
        'inverse-primary': '#6d3bd7',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#363340',
        'surface-container': '#201e2a',
        'outline-variant': '#494454',
        'on-background': '#e6e0f1',
        'secondary-container': '#03b5d3',
        'on-secondary-fixed-variant': '#004e5c',
        'secondary': '#4cd7f6',
        'on-secondary-container': '#00424e',
        'on-primary-fixed': '#23005c',
        'secondary-fixed': '#acedff',
        'primary': '#d0bcff',
        'surface-dim': '#14121d',
        'on-surface': '#e6e0f1',
        'on-secondary': '#003640',
        'inverse-surface': '#e6e0f1',
        'primary-fixed-dim': '#d0bcff',
        'surface-bright': '#3a3744',
        'inverse-on-surface': '#312f3b',
        'on-primary-fixed-variant': '#5516be',
        'on-tertiary-fixed-variant': '#8c0053',
        'on-primary-container': '#340080',
        'surface-tint': '#d0bcff',
        'on-secondary-fixed': '#001f26',
        'on-primary': '#3c0091',
        'error': '#ffb4ab',
        'surface-container-low': '#1c1a26',
        'on-error': '#690005',
        'on-tertiary-container': '#570032',
        'on-tertiary': '#640039',
        'tertiary-fixed': '#ffd9e4',
        'on-surface-variant': '#cbc3d7',
        'primary-fixed': '#e9ddff',
        'outline': '#958ea0',
        'background': '#14121d',
        'primary-container': '#a078ff',
        'surface-container-high': '#2b2835',
        'tertiary': '#ffb0cd',
        'surface-variant': '#363340',
        'tertiary-container': '#f751a1',
        'tertiary-fixed-dim': '#ffb0cd',
        'surface': '#14121d',
        'on-tertiary-fixed': '#3e0022',
        'error-container': '#93000a'
      },
      fontFamily: {
        sans: ['var(--font-jakarta)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
export default config;
